### ISSUE TITLE
Configuration item in nav-bar has wrong URL

### ISSUE THREAD

**Issue by cmeerbeek** [LukeMurphey/splunk-website-monitoring#11]
When you access the Configuration menu-item you get an error saying "Unable to locate the configuration for this URL.".
It should be: "/manager/website_monitoring/apps/local/website_monitoring/setup?action=edit"
Instead of: "/manager/website_input/apps/local/website_monitoring/setup?action=edit"

**Comment by LukeMurphey** [comment]
Good catch.

I fixed this. The fix will be shipped in version 2.0.2.

**Comment by cmeerbeek** [comment]
Your welcome! Good add-on. Really like using it.

**Comment by LukeMurphey** [comment]
FYI: version 2.0.2 has been posted to Splunk-base with a fix.
