### ISSUE TITLE
Is splunk free possible to add new inputs?

### ISSUE THREAD

**Issue by mfvetter** [LukeMurphey/splunk-website-monitoring#12]
On my Splunk free I'm getting this message when trying to create a new input:

> You do not have permission to make Website Monitoring inputs. You are missing the following capabilities: edit_modinput_web_ping, edit_tcp, list_inputs.

So I made the authorize.conf like this in the local folder:

> [capability::edit_modinput_web_ping]
> 
> [role_admin]
> edit_modinput_web_ping = enabled
> 
> [role_power]
> edit_modinput_web_ping = enabled
> 
> 
> [capability::edit_tcp]
> 
> [role_admin]
> edit_tcp = enabled
> 
> [role_power]
> edit_tcp = enabled
> 
> 
> [capability::list_inputs]
> 
> [role_admin]
> list_inputs = enabled
> 
> [role_power]
> list_inputs = enabled

But the message continues, I can't create new inputs. Is this app compatible with splunk free? Am I missing a configuration to be able to create new inputs?

**Comment by hhuy2664** [comment]
Hi mfvetter,
I get the same error on my free splunk as well.
I was able to add new data inputs through Settings > Data Inputs > Website Availability Check
Hope that helps.

**Comment by LukeMurphey** [comment]
I'm going to fix the batch input creator such that it works on the free version of Splunk in version 2.7. That said, the manager page at Settings > Data Inputs > Website Availability Check ought to still work. I just tried it on a 7.0 instance with the free license, and it worked.

**Comment by hhuy2664** [comment]
That is great. Look forward to it.
At the moment, I am editing <SPLUNK_HOME>\etc\apps\website_monitoring\local\inputs.conf for large batch of inputs.

**Comment by LukeMurphey** [comment]
I have a fix for this. It will be included in version 2.8 which should come out very soon (most likely this weekend).
