### ISSUE TITLE
TCP check rather than HTTP/HTTPS?

### ISSUE THREAD

**Issue by binbash12** [LukeMurphey/splunk-website-monitoring#17]
This is more of a feature request rather than a specific issue. I really like this tool and find it handy to use. I'd like to expand the functionality of it to include TCP checks rather than just HTTP/HTTPS checks. Is this in the realm of possibility?

Best regards,
Matt

**Comment by LukeMurphey** [comment]
I have plans to add port scanning to the app. See the ticket here: https://lukemurphey.net/issues/1690

**Comment by LukeMurphey** [comment]
I support this in the Network Toolkit app: https://splunkbase.splunk.com/app/3491/
