### ISSUE TITLE
Splunk Cloud Installation is Rejected

### ISSUE THREAD

**Issue by jeffersongirao** [LukeMurphey/splunk-website-monitoring#18]
Hello! At the moment I'm not being able to install splunk-website-monitoring in a Splunk Cloud installation. It is being rejected with the following report:

Configuration file standards
[ failure ] Check that app does not contain any .conf files that create global definitions using the [default] stanza.
default stanza was found in file: default/website_monitoring.conf. Custom app-specific conf files should avoid [default], [general], [global] stanzas or properties outside of a stanza (treated as default/global). This is discouraged because they may cause some confusion for same stanzas defined by Splunk File: default/website_monitoring.conf

Is it ok the rename default to something else? Thanks in advance.

**Comment by LukeMurphey** [comment]
I'm almost positive you can delete this file because the Python code uses the same defaults. I'll verify that and get back to you.

**Comment by LukeMurphey** [comment]
It looks like I'm wrong. The app is designed in such a way that it assumes that default stanza exists. I'll modify the app such that it no longer requires this file.

I'll also likely take this up with the App Certification Team at Splunk since I don't think the rules should be rejecting the app in this case.

**Comment by jeffersongirao** [comment]
@LukeMurphey Thanks a lot for following up. Please let me know if I can do anything to help as well. Cheers! :)

**Comment by LukeMurphey** [comment]
@jeffersongirao: could you be so kind to try the attached version? I'm hoping this version will be allowed to be installed.

[website_monitoring.tar.gz 2.7](https://github.com/LukeMurphey/splunk-website-monitoring/files/1869036/website_monitoring.tar.gz)

**Comment by jeffersongirao** [comment]
Hello @LukeMurphey! I've tried it and got the same failure: `default stanza was found in file: default/website_monitoring.conf. Custom app-specific conf files should avoid [default], [general], [global] stanzas or properties outside of a stanza (treated as default/global). This is discouraged because they may cause some confusion for same stanzas defined by Splunk File: default/website_monitoring.conf`.

**Comment by LukeMurphey** [comment]
I found a way to test this using the self-service cloud rules. Version 2.7 on Splunk-base should pass now.
