### ISSUE TITLE
NTML Errors not written to log due to small typo.

### ISSUE THREAD

**Issue by csiess** [LukeMurphey/splunk-website-monitoring#19]
Hi,

in web_ping.py, line 736 the correct line should be:
   self.logger.warn('NTLM authentication failed due to configuration issue stanza=%s, message="%s"', stanza, str(e))

message=%s is right, message=%d is wrong.

thanks,
Christoph

**Comment by LukeMurphey** [comment]
Good catch. I fixed this.
