### ISSUE TITLE
Removing old sites

### ISSUE THREAD

**Issue by airforceboricua** [LukeMurphey/splunk-website-monitoring#2]
Hello, 

First, thank you for the app.

Second, question, how do I remove an old site I don't want showing up under Status Overview? I removed the input from Splunk Manager but the site still shows up.

Help please.

**Comment by LukeMurphey** [comment]
I just implemented the ability to filter out old sites on the Status Overview dashboard (with a new checkbox thats filter disabled or removed inputs). It will be released on apps.splunk.com soon.

Code checked into with c6c08accb6a109c3d2017aae877e3f02ff4cb6bf.

**Comment by LukeMurphey** [comment]
This is now present in version 1.1 which is available on https://apps.splunk.com/app/1493/
