### ISSUE TITLE
Should select an specific index for each input created

### ISSUE THREAD

**Issue by rfronteau** [LukeMurphey/splunk-website-monitoring#28]
Hi,

I need to split my data into different index because my different users don't need to see all Website in Monitoring.

It's possible ?

**Comment by LukeMurphey** [comment]
It is.

Open the manager page for the "Website Availability Check" input and click "More Settings". You should see a selector that allows you to select the index where the data ought to go.

See the following for more details: https://lukemurphey.net/projects/splunk-website-monitoring/wiki/Use_An_Alternative_Index

**Comment by rfronteau** [comment]
For each input ?

**Comment by LukeMurphey** [comment]
Right now, thats how it works.

I can add the ability to define the index in the batch input creator though. That won't help you change the existing inputs but it would make creating ones with a custom index easier.

**Comment by rfronteau** [comment]
Yes it's a great idea because I need to Split data collect in different
index because, I have different users and I want :

User1 who access to index1 see url1 and url2 that I param to collect data
on this index

User2 who access to index2 see url3 and url5 that I param to collect data
on this index.

You see interest of this feature ?

Best regards
Romuald

**Comment by rfronteau** [comment]
You should take example of add-on AWS on panel inputs definition ?

We can select on input select list an index created on splunk
infrastructure.

Romuald

Le jeu. 16 mai 2019 à 21:55, Romuald Fronteau <rfronteau@cfsl-asso.org> a
écrit :

> Yes it's a great idea because I need to Split data collect in different
> index because, I have different users and I want :
>
> User1 who access to index1 see url1 and url2 that I param to collect data
> on this index
>
> User2 who access to index2 see url3 and url5 that I param to collect data
> on this index.
>
> You see interest of this feature ?
>
> Best regards
> Romuald
>
