### ISSUE TITLE
Website Availability not pulling in data

### ISSUE THREAD

**Issue by astarr87** [LukeMurphey/splunk-website-monitoring#29]
I have set up my inputs as such:

[web_ping://Google]
interval = 5m
title = Google
url = https://www.google.com
user_agent = Splunk Website Monitoring (+https://splunkbase.splunk.com/app/1493/)

and yet still the app will not pull in any data. I am also not using any proxies and my environment is a single instance deployment. 
Any ideas what could be wrong?

**Comment by LukeMurphey** [comment]
I would recommend looking the troubleshooting steps here: https://lukemurphey.net/projects/splunk-website-monitoring/wiki/Troubleshooting

There is a good chance that will narrow down the issue.
