### ISSUE TITLE
Not working in Splunk Cloud

### ISSUE THREAD

**Issue by zchef2k** [LukeMurphey/splunk-website-monitoring#31]
I had Splunk support install the app this morning and I have configured a couple inputs through Data Inputs -> Website Availability Checks. The sites I'm attempting to monitor are over HTTPS with globally trusted CAs and no authentication. Each time I'm greeted with this:

`2019-07-15 13:02:15,231 ERROR Exception generated when attempting to get the proxy configuration stanza=web_ping://<redacted>, see url=http://lukemurphey.net/projects/splunk-website-monitoring/wiki/Troubleshooting
Traceback (most recent call last):
  File "/opt/splunk/etc/apps/website_monitoring/bin/web_ping.py", line 762, in run_ping
    self.get_proxy_config(input_config.session_key, conf_stanza)
ValueError: need more than 5 values to unpack`

Is there a known issue with cloud? Did I miss additional setup/configuration steps?

**Comment by LukeMurphey** [comment]
I'll look into it today; it is possible that this is a bug.

**Comment by LukeMurphey** [comment]
This is indeed due to a bug. I fixed it in version 2.7.5 (https://splunkbase.splunk.com/app/1493/).
