### ISSUE TITLE
App stops running after TCP Cooked Connections

### ISSUE THREAD

**Issue by j-e-n-k-s-y** [LukeMurphey/splunk-website-monitoring#40]
We're having some kind of issue on our network resulting in UF's throwing TCP Cooked Connections in their _internal logs, but but it's bubbling up in other ways, like the Website Monitor crashing.

Here's the log event we're seeing:

```
2020-03-17 13:31:41,742 ERROR Execution failed
Traceback (most recent call last):
  File "/opt/splunk/etc/apps/website_monitoring/bin/modular_input.py", line 1752, in execute
    self.do_run(in_stream, log_exception_and_continue=True)
  File "/opt/splunk/etc/apps/website_monitoring/bin/modular_input.py", line 1633, in do_run
    self.run(stanza, cleaned_params, input_config)
  File "/opt/splunk/etc/apps/website_monitoring/bin/web_ping.py", line 684, in run
    secure_password = self.get_secure_password(realm=stanza, session_key=input_config.session_key)
  File "/opt/splunk/etc/apps/website_monitoring/bin/modular_input.py", line 1109, in get_secure_password
    return self.get_secure_password_by_realm(realm, session_key)
  File "/opt/splunk/etc/apps/website_monitoring/bin/modular_input.py", line 1134, in get_secure_password_by_realm
    server_response, server_content = splunk.rest.simpleRequest('/services/storage/passwords?output_mode=json', sessionKey=session_key)
  File "/opt/splunk/lib/python2.7/site-packages/splunk/rest/__init__.py", line 500, in simpleRequest
    raise splunk.SplunkdConnectionException, 'Error connecting to %s: %s' % (path, str(e))
SplunkdConnectionException: Splunkd daemon is not responding: ("Error connecting to /services/storage/passwords?output_mode=json: ('The read operation timed out',)",)
```

Is this something that can be added to be handled to gracefully restart?

**Comment by LukeMurphey** [comment]
I actually have the code setup to try to forgive connection failures. Currently, it allows for a 30 second connection failure (tries 6 times and waits 5 seconds between each request).

I'm guessing this isn't sufficiently forgiving. Do you have any idea about how long you would think I ought to expand this to? I'm thinking I should set it to at least several minutes (5 to 30 minutes).

**Comment by j-e-n-k-s-y** [comment]
Thanks for the prompt response.

Based on what we've observed when this falls over, the way you've described the retry mechanism makes me think that might be part of what compounds the problem.  

We're seeing a number of connectivity issues within our Splunk environment right now that we're actively trying to work through, and our Website Monitor tripping up was sort of the canary in the coal mine, which has us now working with support to determine what's going on.

I've been digging through _internal logs and it seems like something within our environment related to volume is tripping us over some kind of connection thresholds, and I'm trying to find evidence that tells us whether it's within our servers hosting Splunk, or within our lower layers of network infrastructure (which is outside of my visibility, at this time).


Specifically to the retry, you can see the issue starting to happen (red box) before the CPU Wait threads start to stack up on the servers running these checks (orange box):

![image](https://user-images.githubusercontent.com/2670528/76909980-6186b500-6872-11ea-906b-4adce274b419.png)



This error presented at 12:26, 13:31, and 13:41 today, which all correspond with the CPU Wait.  connections failing prior were recovering and populating data (though intermittantly) for a time leading up to the crash.

With the CPU Threads stacking, I suspect that's ultimately what leads the Splunk Web UI to fail to load on that server, which was experienced today when checking the data inputs immediately after receiving an alert for this condition.   I suspect if the wait threads didn't back up, the UI wouldn't have hung, and the internal call to the passwords storage URL referenced in the time out wouldn't have occurred?


If a website check fails, I would wait for that failure before retrying again to prevent thread queueing.  Perhaps the number of retries could be obtained by dividing the Interval (set in the Input) by the Timeout, so a 1m interval would retry every 30 seconds, twice per minute, but an interval of 5m could retry 10 times (300 seconds / 30 second timeout = 10) before the next interval.

If the code triggers each time an interval is fired, the formula **Interval / Timeout = Request Retry Delay** might work?

**Comment by j-e-n-k-s-y** [comment]
After reviewing your addon and installing on another server, I noticed the Thread Limit default of 200.

We tried increasing it, but it didn't 'stick', and reverted back to 200.

Based on the retry mechanism you indicate, I suspect we're hitting thread limits, caused by the retry mechanism spread across 70+ website checks.


I've updated the app to the latest (we were a couple behind), and it seems to have eliminated the crashing.  I should have done that first before opening this case; please feel free to mark this completed -- we continue to receive cooked connections, but your web check add-on remains tolerant!

**Comment by LukeMurphey** [comment]
I made a changed that might affect this issue somewhat. The app now caches the REST calls for a few minutes and thus connects to splunkd far less frequently.
