### ISSUE TITLE
Detailed Error logs? 

### ISSUE THREAD

**Issue by tb582** [LukeMurphey/splunk-website-monitoring#43]
Is there a way to get detailed logs from the Website Monitoring app that will tell me what IP it was routed to when running its tests? I have on  Include Raw Output and  Include Response HTTP Headers but its not giving me the hop info I'm looking for :(

**Comment by tb582** [comment]
@LukeMurphey  ?

**Comment by LukeMurphey** [comment]
I had looked into this in the past and was unable to get the underlying library to include the IP. I am seeing that some people may have been able to figure out a solution. Let me try it and see if it works.

**Comment by LukeMurphey** [comment]
I spent some time on this. Unfortunately, I still don't have a good way to get the IP. I have some notes here: https://lukemurphey.net/issues/2806
