### ISSUE TITLE
Please make this available to Splunk Cloud

### ISSUE THREAD

**Issue by j-chia** [LukeMurphey/splunk-website-monitoring#48]
Thank you very much for the very useful app. I am now migrating Splunk onprem to Splunk Cloud, and found out that the Website Monitoring app is "not yet available for Splunk Cloud." Many of our websites depended on this app. Is making this available/compatible to Splunk Cloud in your pipeline? If yes, is there an ETA? This will answer many of the questions I am getting. Thank you!

**Comment by LukeMurphey** [comment]
I uploaded a new version of the app with fixes that should allow the app to be installed on Cloud. I'm currently waiting for the app to be approved for Cloud install.
